# -*- mode: ruby -*-
# vi: set ft=ruby :

def install_plugin(plugin)
  system "vagrant plugin install #{plugin}" unless Vagrant.has_plugin? plugin
end

# install plugins
#install_plugin('vagrant-vbguest')
#install_plugin('vagrant-hostmanager')
#install_plugin('sahara')
#install_plugin('vagrant-vbox-snapshot')
#install_plugin('vagrant-reload')

Vagrant.configure("2") do |config|

  # dfault host
  config.vm.box = "generic/rocky9"
  config.vm.network "private_network", ip: "192.168.56.11"
  #config.vm.network "forwarded_port", guest: 80, host: 41080 # http
  config.vm.provider :virtualbox do |vb|
    vb.name = "testansible01"
    vb.gui = false
    vb.memory = "2048"
    vb.cpus = 2
    vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
  end

  ## host01
  #config.vm.define "host01" do |host01|
  #  host01.vm.box = "generic/rocky9"
  #  host01.vm.network "private_network", ip: "192.168.56.11"
  #  #host01.vm.network "forwarded_port", guest: 80, host: 41080 # http
  #  host01.vm.provider :virtualbox do |vb|
  #    vb.name = "testansible01"
  #    vb.gui = false
  #    vb.memory = "2048"
  #    vb.cpus = 2
  #    vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
  #    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
  #  end
  #end

  # host02
  #config.vm.define "host02" do |host02|
  #  host02.vm.box = "generic/rocky9"
  #  host02.vm.network "private_network", ip: "192.168.56.12"
  #  #host02.vm.network "forwarded_port", guest: 80, host: 42080 # http
  #  host02.vm.provider :virtualbox do |vb|
  #    vb.name = "testansible02"
  #    vb.gui = false
  #    vb.memory = "1024"
  #    vb.cpus = 1
  #    vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
  #    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
  #  end
  #end

  ## host03
  #config.vm.define "host03" do |host03|
  #  host03.vm.box = "generic/rocky9"
  #  host03.vm.network "private_network", ip: "192.168.56.13"
  #  #host03.vm.network "forwarded_port", guest: 80, host: 43080 # http
  #  host03.vm.provider :virtualbox do |vb|
  #    vb.name = "testansible03"
  #    vb.gui = false
  #    vb.memory = "1024"
  #    vb.cpus = 1
  #    vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
  #    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
  #  end
  #end

  ## host04
  #config.vm.define "host04" do |host04|
  #  host04.vm.box = "generic/rocky9"
  #  host04.vm.network "private_network", ip: "192.168.56.14"
  #  #host04.vm.network "forwarded_port", guest: 80, host: 44080 # http
  #  host04.vm.provider :virtualbox do |vb|
  #    vb.name = "testansible04"
  #    vb.gui = false
  #    vb.memory = "1024"
  #    vb.cpus = 1
  #    vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
  #    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
  #  end
  #end

  ## host05
  #config.vm.define "host05" do |host05|
  #  host05.vm.box = "generic/rocky9"
  #  host05.vm.network "private_network", ip: "192.168.56.15"
  #  #host05.vm.network "forwarded_port", guest: 80, host: 45080 # http
  #  host05.vm.provider :virtualbox do |vb|
  #    vb.name = "testansible05"
  #    vb.gui = false
  #    vb.memory = "1024"
  #    vb.cpus = 1
  #    vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
  #    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
  #  end
  #end

  ## host06
  #config.vm.define "host06" do |host06|
  #  host06.vm.box = "generic/rocky9"
  #  host06.vm.network "private_network", ip: "192.168.56.16"
  #  #host06.vm.network "forwarded_port", guest: 80, host: 46080 # http
  #  host06.vm.provider :virtualbox do |vb|
  #    vb.name = "testansible06"
  #    vb.gui = false
  #    vb.memory = "1024"
  #    vb.cpus = 1
  #    vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
  #    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
  #  end
  #end

  ## host07
  #config.vm.define "host07" do |host07|
  #  host07.vm.box = "generic/rocky9"
  #  host07.vm.network "private_network", ip: "192.168.56.17"
  #  #host07.vm.network "forwarded_port", guest: 80, host: 47080 # http
  #  host07.vm.provider :virtualbox do |vb|
  #    vb.name = "testansible07"
  #    vb.gui = false
  #    vb.memory = "1024"
  #    vb.cpus = 1
  #    vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
  #    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
  #  end
  #end

  ## host08
  #config.vm.define "host08" do |host08|
  #  host08.vm.box = "generic/rocky9"
  #  host08.vm.network "private_network", ip: "192.168.56.18"
  #  #host08.vm.network "forwarded_port", guest: 80, host: 48080 # http
  #  host08.vm.provider :virtualbox do |vb|
  #    vb.name = "testansible08"
  #    vb.gui = false
  #    vb.memory = "1024"
  #    vb.cpus = 1
  #    vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
  #    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
  #  end
  #end

  config.vm.provision :ansible do |ansible|
    playbook_dir = "../ansible/playbook"
    ansible.config_file = playbook_dir + "/ansible.cfg"
    ansible.playbook = playbook_dir + "/site_all_setup.yml"
    ansible.inventory_path = playbook_dir + "/inventories/vagrant_hosts.yml"
    ansible.limit = 'all'
    #ansible.verbose = "vvv"
    #ansible.tags = "tag1,tag2,..."
    #ansible.tags = "os,mariadb"
  end
end
